FROM golang:1.23.5-alpine

WORKDIR /app

# Install air
RUN go install github.com/air-verse/air@latest

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application
COPY . .

# Run air
CMD ["air", "-c", ".air.toml"]